Thrift utils refactoring
valitydev/control-center pull request #19
Opened 2022-01-21 13:44 UTC by KeinAsylum

2022-01-24 08:04 UTC, KrickRay requested changes

2022-01-26 15:36 UTC, KeinAsylum commented on src/app/api/thrift-instance-provider/types/provider-methods.ts
> +    toThriftInstance<T>(indefiniteType: ValueType, plainObject: T): T;
При необходимости можно будет добавить что-то вроде: `toPlainObjectNS(ns: string, indefiniteType: ValueType, thriftInstance: T): T`, не должно быть проблем

2022-01-26 16:18 UTC, KrickRay requested changes

2022-01-26 16:18 UTC, KrickRay commented on src/app/api/thrift-instance-provider/thrift-instance-provider.service.ts
> +            first()
теперь грузит каждый раз json

2022-01-27 10:35 UTC, KrickRay approved these changes

2022-01-27 10:36 UTC, merged